const LANGS={
 it:{navStore:'Beat Store',how:'Come funziona',license:'Licenza',contact:'Contatti',heroEy:'STRUMENTALI ORIGINALI · RODRIGO HITS',beat:'beat',hero1:'Trova il beat.',hero2:'Fallo tuo.',heroP:'Strumentali originali pensate per artisti che vogliono un sound con identità. Ascolta le demo, trova la tua direzione e invia una richiesta.',explore:'ESPLORA I BEAT',howBtn:'COME FUNZIONA',noCheckout:'NESSUN CHECKOUT AUTOMATICO',personal:'Ogni richiesta viene gestita personalmente.',catalog:'IL CATALOGO',choose:'Scegli il tuo sound.',saved:'SALVATI',search:'Cerca beat, genere, mood o BPM...',allGenres:'Tutti i generi',allMoods:'Tutti i mood',min:'BPM min',max:'BPM max',newest:'Più recenti',low:'BPM: basso → alto',high:'BPM: alto → basso',az:'A → Z',clear:'AZZERA FILTRI',noResults:'Nessun beat trovato.',previous:'← PRECEDENTE',next:'SUCCESSIVO →',simple:'PROCESSO SEMPLICE',fromIdea:'Dall’idea\nal disco.',howP:'Trova il tuo sound senza un checkout complicato. Licenza e consegna finale vengono organizzate direttamente con Rodrigo.',listen:'ASCOLTA',find:'Trova il tuo sound',listenP:'Esplora il catalogo e ascolta la demo più adatta alla tua idea.',request:'RICHIEDI',sendReq:'Invia una richiesta',requestP:'Scegli il beat e raccontaci chi sei e cosa vuoi creare.',connect:'CONTATTO',talk:'Parla direttamente',talkP:'Rodrigo ti contatta personalmente per licenza, prezzo e consegna.',licenseEy:'LICENZA & CONSEGNA',release:'Dalla richiesta\nalla release.',licenseP:'Ogni strumentale viene gestita personalmente. Nessun checkout o download automatico.',req:'Richiesta',reqP:'Scegli il beat e invia la richiesta dal Beat Store.',discuss:'Confronto',discussP:'Rodrigo ti contatta direttamente per definire le condizioni del progetto.',lic:'Licenza',licP:'La licenza adatta e il prezzo vengono concordati direttamente con te.',delivery:'Consegna',deliveryP:'Dopo il pagamento concordato, la strumentale viene preparata e consegnata direttamente.',noAuto:'NESSUN CHECKOUT AUTOMATICO.',noDownload:'NESSUN DOWNLOAD AUTOMATICO.',personalContact:'CONTATTO PERSONALE',requestEy:'RICHIEDI UN BEAT',found:'Hai trovato quello giusto?',contactP:'Invia la tua richiesta. Nessun pagamento automatico, nessun download automatico — solo un contatto diretto sul beat che vuoi.',artist:'Artista / Nome',email:'Email',beat:'Beat',selectBeat:'Seleziona un beat',message:'Messaggio',messagePh:'Raccontaci qualcosa di utile sul tuo progetto...',send:'INVIA RICHIESTA',mailNote:'Si aprirà la tua app email con la richiesta già preparata.',footer:'Strumentali originali',details:'DETTAGLI BEAT',play:'RIPRODUCI DEMO',playing:'IN RIPRODUZIONE',modalLicense:'LICENZA & CONSEGNA',modalReq:'Richiedi la strumentale',modalPrev:'← PRECEDENTE',modalNext:'SUCCESSIVO →',genre:'Genere',mood:'Mood'},
 en:{navStore:'Beat Store',how:'How it works',license:'License',contact:'Contact',heroEy:'ORIGINAL INSTRUMENTALS · RODRIGO HITS',hero1:'Find the beat.',hero2:'Make it yours.',heroP:'Original instrumentals built for artists who want a sound with identity. Listen to the demos, find your direction and send a request.',explore:'EXPLORE THE BEATS',howBtn:'HOW IT WORKS',noCheckout:'NO AUTOMATIC CHECKOUT',personal:'Every beat request is handled personally.',catalog:'THE CATALOG',choose:'Choose your sound.',saved:'SAVED',search:'Search beat, genre, mood or BPM...',allGenres:'All genres',allMoods:'All moods',min:'Min BPM',max:'Max BPM',newest:'Newest',low:'BPM: low → high',high:'BPM: high → low',az:'A → Z',clear:'CLEAR FILTERS',noResults:'No beats found.',previous:'← PREVIOUS',next:'NEXT →',simple:'SIMPLE PROCESS',fromIdea:'From idea\nto record.',howP:'Find your sound without a complicated checkout. The final license and delivery are arranged directly with Rodrigo.',listen:'LISTEN',find:'Find your sound',listenP:'Explore the catalog and play the demo that fits your idea.',request:'REQUEST',sendReq:'Send a request',requestP:'Choose the beat and tell us who you are and what you want to create.',connect:'CONNECT',talk:'Talk directly',talkP:'Rodrigo contacts you personally about license, price and delivery.',licenseEy:'LICENSE & DELIVERY',release:'From request\nto release.',licenseP:'Every instrumental is handled personally. There is no automatic checkout or automatic download.',req:'Request',reqP:'Choose your beat and send your request from the Beat Store.',discuss:'Discuss',discussP:'Rodrigo contacts you directly to define the conditions for your project.',lic:'License',licP:'The appropriate license and its price are agreed directly with you.',delivery:'Delivery',deliveryP:'After the agreed payment, the instrumental is prepared and delivered directly.',noAuto:'NO AUTOMATIC CHECKOUT.',noDownload:'NO AUTOMATIC DOWNLOAD.',personalContact:'PERSONAL CONTACT.',requestEy:'REQUEST A BEAT',found:'Found the one?',contactP:'Send your request. No automatic payment, no automatic download — just a direct conversation about the beat you want.',artist:'Artist / Name',email:'Email',beat:'Beat',selectBeat:'Select a beat',message:'Message',messagePh:'Tell us anything relevant about your project...',send:'SEND REQUEST',mailNote:'Your email app will open with the request prepared.',footer:'Original instrumentals',details:'BEAT DETAILS',play:'PLAY DEMO',playing:'PLAYING',modalLicense:'LICENSE & DELIVERY',modalReq:'REQUEST THIS BEAT',modalPrev:'← PREVIOUS',modalNext:'NEXT →',genre:'Genre',mood:'Mood'},
 es:{navStore:'Beat Store',how:'Cómo funciona',license:'Licencia',contact:'Contacto',heroEy:'INSTRUMENTALES ORIGINALES · RODRIGO HITS',hero1:'Encuentra el beat.',hero2:'Hazlo tuyo.',heroP:'Instrumentales originales creados para artistas que buscan un sonido con identidad. Escucha las demos, encuentra tu dirección y envía una solicitud.',explore:'EXPLORAR BEATS',howBtn:'CÓMO FUNCIONA',noCheckout:'SIN CHECKOUT AUTOMÁTICO',personal:'Cada solicitud se gestiona personalmente.',catalog:'EL CATÁLOGO',choose:'Elige tu sonido.',saved:'GUARDADOS',search:'Busca beat, género, mood o BPM...',allGenres:'Todos los géneros',allMoods:'Todos los moods',min:'BPM mín.',max:'BPM máx.',newest:'Más recientes',low:'BPM: bajo → alto',high:'BPM: alto → bajo',az:'A → Z',clear:'BORRAR FILTROS',noResults:'No se encontraron beats.',previous:'← ANTERIOR',next:'SIGUIENTE →',simple:'PROCESO SIMPLE',fromIdea:'De la idea\nal disco.',howP:'Encuentra tu sonido sin un checkout complicado. La licencia y la entrega final se gestionan directamente con Rodrigo.',listen:'ESCUCHA',find:'Encuentra tu sonido',listenP:'Explora el catálogo y reproduce la demo que encaje con tu idea.',request:'SOLICITUD',sendReq:'Envía una solicitud',requestP:'Elige el beat y cuéntanos quién eres y qué quieres crear.',connect:'CONTACTO',talk:'Habla directamente',talkP:'Rodrigo te contacta personalmente sobre licencia, precio y entrega.',licenseEy:'LICENCIA Y ENTREGA',release:'De la solicitud\nal lanzamiento.',licenseP:'Cada instrumental se gestiona personalmente. No hay checkout ni descarga automática.',req:'Solicitud',reqP:'Elige tu beat y envía la solicitud desde el Beat Store.',discuss:'Acuerdo',discussP:'Rodrigo te contacta para definir las condiciones de tu proyecto.',lic:'Licencia',licP:'La licencia adecuada y su precio se acuerdan directamente contigo.',delivery:'Entrega',deliveryP:'Tras el pago acordado, la instrumental se prepara y se entrega directamente.',noAuto:'SIN CHECKOUT AUTOMÁTICO.',noDownload:'SIN DESCARGA AUTOMÁTICA.',personalContact:'CONTACTO PERSONAL',requestEy:'SOLICITA UN BEAT',found:'¿Encontraste el indicado?',contactP:'Envía tu solicitud. Sin pago automático, sin descarga automática — solo una conversación directa sobre el beat que quieres.',artist:'Artista / Nombre',email:'Email',beat:'Beat',selectBeat:'Selecciona un beat',message:'Mensaje',messagePh:'Cuéntanos algo relevante sobre tu proyecto...',send:'ENVIAR SOLICITUD',mailNote:'Se abrirá tu app de correo con la solicitud preparada.',footer:'Instrumentales originales',details:'DETALLES DEL BEAT',play:'REPRODUCIR DEMO',playing:'REPRODUCIENDO',modalLicense:'LICENCIA Y ENTREGA',modalReq:'SOLICITAR ESTE BEAT',modalPrev:'← ANTERIOR',modalNext:'SIGUIENTE →',genre:'Género',mood:'Mood'},
 fr:{navStore:'Beat Store',how:'Comment ça marche',license:'Licence',contact:'Contact',heroEy:'INSTRUMENTALES ORIGINALES · RODRIGO HITS',hero1:'Trouve le beat.',hero2:'Fais-le tien.',heroP:'Des instrumentales originales pour les artistes qui veulent un son avec une identité. Écoute les démos, trouve ta direction et envoie une demande.',explore:'EXPLORER LES BEATS',howBtn:'COMMENT ÇA MARCHE',noCheckout:'SANS PAIEMENT AUTOMATIQUE',personal:'Chaque demande est traitée personnellement.',catalog:'LE CATALOGUE',choose:'Choisis ton son.',saved:'ENREGISTRÉS',search:'Rechercher beat, genre, mood ou BPM...',allGenres:'Tous les genres',allMoods:'Tous les moods',min:'BPM min.',max:'BPM max.',newest:'Plus récents',low:'BPM : bas → haut',high:'BPM : haut → bas',az:'A → Z',clear:'EFFACER LES FILTRES',noResults:'Aucun beat trouvé.',previous:'← PRÉCÉDENT',next:'SUIVANT →',simple:'PROCESSUS SIMPLE',fromIdea:'De l’idée\nau morceau.',howP:'Trouve ton son sans checkout compliqué. La licence et la livraison finale sont organisées directement avec Rodrigo.',listen:'ÉCOUTER',find:'Trouve ton son',listenP:'Explore le catalogue et écoute la démo qui correspond à ton idée.',request:'DEMANDE',sendReq:'Envoyer une demande',requestP:'Choisis le beat et dis-nous qui tu es et ce que tu veux créer.',connect:'CONTACT',talk:'Parle directement',talkP:'Rodrigo te contacte personnellement pour la licence, le prix et la livraison.',licenseEy:'LICENCE & LIVRAISON',release:'De la demande\nà la sortie.',licenseP:'Chaque instrumentale est gérée personnellement. Aucun checkout ni téléchargement automatique.',req:'Demande',reqP:'Choisis ton beat et envoie ta demande depuis le Beat Store.',discuss:'Échange',discussP:'Rodrigo te contacte directement pour définir les conditions du projet.',lic:'Licence',licP:'La licence adaptée et son prix sont convenus directement avec toi.',delivery:'Livraison',deliveryP:'Après le paiement convenu, l’instrumentale est préparée et livrée directement.',noAuto:'SANS CHECKOUT AUTOMATIQUE.',noDownload:'SANS TÉLÉCHARGEMENT AUTOMATIQUE.',personalContact:'CONTACT PERSONNEL',requestEy:'DEMANDER UN BEAT',found:'Tu as trouvé le bon ?',contactP:'Envoie ta demande. Aucun paiement automatique, aucun téléchargement automatique — juste un échange direct sur le beat que tu veux.',artist:'Artiste / Nom',email:'Email',beat:'Beat',selectBeat:'Sélectionner un beat',message:'Message',messagePh:'Dis-nous ce qui est utile pour ton projet...',send:'ENVOYER LA DEMANDE',mailNote:'Ton application mail s’ouvrira avec la demande préparée.',footer:'Instrumentales originales',details:'DÉTAILS DU BEAT',play:'ÉCOUTER LA DÉMO',playing:'LECTURE',modalLicense:'LICENCE & LIVRAISON',modalReq:'DEMANDER CE BEAT',modalPrev:'← PRÉCÉDENT',modalNext:'SUIVANT →',genre:'Genre',mood:'Mood'},
 de:{navStore:'Beat Store',how:'So funktioniert es',license:'Lizenz',contact:'Kontakt',heroEy:'ORIGINAL INSTRUMENTALS · RODRIGO HITS',hero1:'Finde den Beat.',hero2:'Mach ihn zu deinem.',heroP:'Originale Instrumentals für Artists mit eigenem Sound. Demos anhören, Richtung finden und Anfrage senden.',explore:'BEATS ENTDECKEN',howBtn:'SO FUNKTIONIERT ES',noCheckout:'KEIN AUTOMATISCHER CHECKOUT',personal:'Jede Anfrage wird persönlich bearbeitet.',catalog:'DER KATALOG',choose:'Wähle deinen Sound.',saved:'GESPEICHERT',search:'Beat, Genre, Mood oder BPM suchen...',allGenres:'Alle Genres',allMoods:'Alle Moods',min:'Min. BPM',max:'Max. BPM',newest:'Neueste',low:'BPM: niedrig → hoch',high:'BPM: hoch → niedrig',az:'A → Z',clear:'FILTER LÖSCHEN',noResults:'Keine Beats gefunden.',previous:'← ZURÜCK',next:'WEITER →',simple:'EINFACHER PROZESS',fromIdea:'Von der Idee\nzum Release.',howP:'Finde deinen Sound ohne komplizierten Checkout. Lizenz und Lieferung werden direkt mit Rodrigo vereinbart.',listen:'HÖREN',find:'Sound finden',listenP:'Durchsuche den Katalog und spiele die passende Demo ab.',request:'ANFRAGE',sendReq:'Anfrage senden',requestP:'Wähle den Beat und erzähle uns, wer du bist und was du erstellen möchtest.',connect:'KONTAKT',talk:'Direkt sprechen',talkP:'Rodrigo kontaktiert dich persönlich zu Lizenz, Preis und Lieferung.',licenseEy:'LIZENZ & LIEFERUNG',release:'Von der Anfrage\nzum Release.',licenseP:'Jedes Instrumental wird persönlich betreut. Kein automatischer Checkout oder Download.',req:'Anfrage',reqP:'Wähle deinen Beat und sende die Anfrage aus dem Beat Store.',discuss:'Besprechen',discussP:'Rodrigo kontaktiert dich direkt, um die Bedingungen deines Projekts festzulegen.',lic:'Lizenz',licP:'Die passende Lizenz und der Preis werden direkt mit dir vereinbart.',delivery:'Lieferung',deliveryP:'Nach der vereinbarten Zahlung wird das Instrumental vorbereitet und direkt geliefert.',noAuto:'KEIN AUTOMATISCHER CHECKOUT.',noDownload:'KEIN AUTOMATISCHER DOWNLOAD.',personalContact:'PERSÖNLICHER KONTAKT',requestEy:'BEAT ANFRAGEN',found:'Den richtigen gefunden?',contactP:'Sende deine Anfrage. Keine automatische Zahlung, kein automatischer Download — nur ein direktes Gespräch über den gewünschten Beat.',artist:'Artist / Name',email:'E-Mail',beat:'Beat',selectBeat:'Beat auswählen',message:'Nachricht',messagePh:'Erzähl uns etwas Relevantes über dein Projekt...',send:'ANFRAGE SENDEN',mailNote:'Deine Mail-App öffnet sich mit der vorbereiteten Anfrage.',footer:'Original Instrumentals',details:'BEAT-DETAILS',play:'DEMO ABSPIELEN',playing:'WIRD ABGESPIELT',modalLicense:'LIZENZ & LIEFERUNG',modalReq:'BEAT ANFRAGEN',modalPrev:'← ZURÜCK',modalNext:'WEITER →',genre:'Genre',mood:'Mood'},
 pt:{navStore:'Beat Store',how:'Como funciona',license:'Licença',contact:'Contacto',heroEy:'INSTRUMENTAIS ORIGINAIS · RODRIGO HITS',hero1:'Encontra o beat.',hero2:'Faz dele o teu.',heroP:'Instrumentais originais para artistas que procuram um som com identidade. Ouve as demos, encontra a tua direção e envia um pedido.',explore:'EXPLORAR BEATS',howBtn:'COMO FUNCIONA',noCheckout:'SEM CHECKOUT AUTOMÁTICO',personal:'Cada pedido é tratado pessoalmente.',catalog:'O CATÁLOGO',choose:'Escolhe o teu som.',saved:'GUARDADOS',search:'Pesquisar beat, género, mood ou BPM...',allGenres:'Todos os géneros',allMoods:'Todos os moods',min:'BPM mín.',max:'BPM máx.',newest:'Mais recentes',low:'BPM: baixo → alto',high:'BPM: alto → baixo',az:'A → Z',clear:'LIMPAR FILTROS',noResults:'Nenhum beat encontrado.',previous:'← ANTERIOR',next:'SEGUINTE →',simple:'PROCESSO SIMPLES',fromIdea:'Da ideia\nao lançamento.',howP:'Encontra o teu som sem um checkout complicado. A licença e a entrega final são tratadas diretamente com Rodrigo.',listen:'OUVIR',find:'Encontra o teu som',listenP:'Explora o catálogo e ouve a demo certa para a tua ideia.',request:'PEDIDO',sendReq:'Enviar um pedido',requestP:'Escolhe o beat e diz-nos quem és e o que queres criar.',connect:'CONTACTO',talk:'Fala diretamente',talkP:'Rodrigo contacta-te pessoalmente sobre licença, preço e entrega.',licenseEy:'LICENÇA & ENTREGA',release:'Do pedido\nao lançamento.',licenseP:'Cada instrumental é tratado pessoalmente. Sem checkout ou download automático.',req:'Pedido',reqP:'Escolhe o beat e envia o pedido no Beat Store.',discuss:'Conversa',discussP:'Rodrigo contacta-te diretamente para definir as condições do projeto.',lic:'Licença',licP:'A licença adequada e o preço são acordados diretamente contigo.',delivery:'Entrega',deliveryP:'Após o pagamento acordado, o instrumental é preparado e entregue diretamente.',noAuto:'SEM CHECKOUT AUTOMÁTICO.',noDownload:'SEM DOWNLOAD AUTOMÁTICO.',personalContact:'CONTACTO PESSOAL',requestEy:'PEDIR UM BEAT',found:'Encontraste o certo?',contactP:'Envia o teu pedido. Sem pagamento automático, sem download automático — apenas uma conversa direta sobre o beat que queres.',artist:'Artista / Nome',email:'Email',beat:'Beat',selectBeat:'Selecionar um beat',message:'Mensagem',messagePh:'Conta-nos algo relevante sobre o teu projeto...',send:'ENVIAR PEDIDO',mailNote:'A tua aplicação de email abrirá com o pedido preparado.',footer:'Instrumentais originais',details:'DETALHES DO BEAT',play:'OUVIR DEMO',playing:'A REPRODUZIR',modalLicense:'LICENÇA & ENTREGA',modalReq:'PEDIR ESTE BEAT',modalPrev:'← ANTERIOR',modalNext:'SEGUINTE →',genre:'Género',mood:'Mood'},
 zh:{navStore:'节拍商店',how:'使用方式',license:'授权',contact:'联系',heroEy:'原创伴奏 · RODRIGO HITS',hero1:'找到你的节拍。',hero2:'让它属于你。',heroP:'为追求独特声音的音乐人打造原创伴奏。试听 Demo，找到方向并提交需求。',explore:'浏览节拍',howBtn:'使用方式',noCheckout:'无自动结账',personal:'每个需求都由本人亲自处理。',catalog:'节拍目录',choose:'选择你的声音。',saved:'已收藏',search:'搜索节拍、风格、氛围或 BPM...',allGenres:'全部风格',allMoods:'全部氛围',min:'最低 BPM',max:'最高 BPM',newest:'最新',low:'BPM：低 → 高',high:'BPM：高 → 低',az:'A → Z',clear:'清除筛选',noResults:'没有找到节拍。',previous:'← 上一页',next:'下一页 →',simple:'简单流程',fromIdea:'从灵感\n到作品。',howP:'无需复杂结账。授权和最终交付将直接与 Rodrigo 协商。',listen:'试听',find:'找到你的声音',listenP:'浏览目录并试听适合你的 Demo。',request:'申请',sendReq:'提交申请',requestP:'选择节拍并告诉我们你的项目。',connect:'联系',talk:'直接沟通',talkP:'Rodrigo 会亲自联系你讨论授权、价格和交付。',licenseEy:'授权与交付',release:'从申请\n到发布。',licenseP:'每个伴奏都由本人处理，不提供自动结账或自动下载。',req:'申请',reqP:'选择节拍并从 Beat Store 提交申请。',discuss:'沟通',discussP:'Rodrigo 直接联系你确定项目条件。',lic:'授权',licP:'合适的授权和价格与你直接协商。',delivery:'交付',deliveryP:'付款确认后，伴奏将准备并直接交付。',noAuto:'无自动结账。',noDownload:'无自动下载。',personalContact:'人工联系',requestEy:'申请节拍',found:'找到合适的吗？',contactP:'提交申请。无自动付款、无自动下载，只为你想要的节拍进行直接沟通。',artist:'艺人 / 姓名',email:'邮箱',beat:'节拍',selectBeat:'选择节拍',message:'留言',messagePh:'告诉我们你的项目...',send:'提交申请',mailNote:'你的邮件应用将打开并自动准备申请内容。',footer:'原创伴奏',details:'节拍详情',play:'试听 DEMO',playing:'播放中',modalLicense:'授权与交付',modalReq:'申请此节拍',modalPrev:'← 上一个',modalNext:'下一个 →',genre:'风格',mood:'氛围'},
 ja:{navStore:'ビートストア',how:'利用方法',license:'ライセンス',contact:'お問い合わせ',heroEy:'オリジナル・インストゥルメンタル · RODRIGO HITS',hero1:'ビートを見つける。',hero2:'自分の音にする。',heroP:'個性あるサウンドを求めるアーティストのためのオリジナル・インストゥルメンタル。デモを聴いて、方向性を見つけ、リクエストを送れます。',explore:'ビートを見る',howBtn:'利用方法',noCheckout:'自動決済なし',personal:'すべてのリクエストを個別に対応します。',catalog:'カタログ',choose:'サウンドを選ぶ。',saved:'保存済み',search:'ビート、ジャンル、ムード、BPMを検索...',allGenres:'すべてのジャンル',allMoods:'すべてのムード',min:'最低 BPM',max:'最高 BPM',newest:'新着',low:'BPM：低 → 高',high:'BPM：高 → 低',az:'A → Z',clear:'フィルターをクリア',noResults:'ビートが見つかりません。',previous:'← 前へ',next:'次へ →',simple:'シンプルな流れ',fromIdea:'アイデアから\n作品へ。',howP:'複雑な決済はありません。ライセンスと最終納品は Rodrigo と直接相談します。',listen:'試聴',find:'サウンドを探す',listenP:'カタログからイメージに合うデモを試聴できます。',request:'リクエスト',sendReq:'リクエストを送る',requestP:'ビートを選び、あなたとプロジェクトについて教えてください。',connect:'コンタクト',talk:'直接相談',talkP:'ライセンス、価格、納品について Rodrigo が直接連絡します。',licenseEy:'ライセンス & 納品',release:'リクエストから\nリリースへ。',licenseP:'すべてのインストゥルメンタルを個別に対応。自動決済・自動ダウンロードはありません。',req:'リクエスト',reqP:'ビートを選んで Beat Store からリクエストを送信。',discuss:'相談',discussP:'Rodrigo が直接連絡し、プロジェクト条件を決めます。',lic:'ライセンス',licP:'最適なライセンスと価格を直接相談します。',delivery:'納品',deliveryP:'合意した支払い後、インストゥルメンタルを準備して直接納品します。',noAuto:'自動決済なし。',noDownload:'自動ダウンロードなし。',personalContact:'直接対応',requestEy:'ビートをリクエスト',found:'見つかりましたか？',contactP:'リクエストを送信。自動決済も自動ダウンロードもなく、欲しいビートについて直接相談できます。',artist:'アーティスト / 名前',email:'メール',beat:'ビート',selectBeat:'ビートを選択',message:'メッセージ',messagePh:'プロジェクトについて教えてください...',send:'リクエストを送信',mailNote:'メールアプリが開き、リクエストが準備されます。',footer:'オリジナル・インストゥルメンタル',details:'ビート詳細',play:'デモを再生',playing:'再生中',modalLicense:'ライセンス & 納品',modalReq:'このビートをリクエスト',modalPrev:'← 前へ',modalNext:'次へ →',genre:'ジャンル',mood:'ムード'},
 ko:{navStore:'비트 스토어',how:'이용 방법',license:'라이선스',contact:'문의',heroEy:'오리지널 인스트루멘털 · RODRIGO HITS',hero1:'비트를 찾으세요.',hero2:'당신의 것으로.',heroP:'자신만의 사운드를 원하는 아티스트를 위한 오리지널 인스트루멘털. 데모를 듣고 방향을 찾은 뒤 요청을 보내세요.',explore:'비트 둘러보기',howBtn:'이용 방법',noCheckout:'자동 결제 없음',personal:'모든 요청은 직접 처리됩니다.',catalog:'카탈로그',choose:'사운드를 선택하세요.',saved:'저장됨',search:'비트, 장르, 무드 또는 BPM 검색...',allGenres:'모든 장르',allMoods:'모든 무드',min:'최소 BPM',max:'최대 BPM',newest:'최신순',low:'BPM: 낮은 순 → 높은 순',high:'BPM: 높은 순 → 낮은 순',az:'A → Z',clear:'필터 초기화',noResults:'비트를 찾을 수 없습니다.',previous:'← 이전',next:'다음 →',simple:'간단한 과정',fromIdea:'아이디어에서\n음원으로.',howP:'복잡한 결제 없이 사운드를 찾으세요. 라이선스와 최종 전달은 Rodrigo와 직접 진행합니다.',listen:'듣기',find:'사운드 찾기',listenP:'카탈로그를 둘러보고 아이디어에 맞는 데모를 재생하세요.',request:'요청',sendReq:'요청 보내기',requestP:'비트를 선택하고 당신과 프로젝트에 대해 알려주세요.',connect:'연락',talk:'직접 상담',talkP:'Rodrigo가 라이선스, 가격, 전달에 대해 직접 연락합니다.',licenseEy:'라이선스 & 전달',release:'요청에서\n발매까지.',licenseP:'모든 인스트루멘털은 직접 관리합니다. 자동 결제나 자동 다운로드가 없습니다.',req:'요청',reqP:'비트를 선택하고 Beat Store에서 요청을 보내세요.',discuss:'상담',discussP:'Rodrigo가 직접 연락해 프로젝트 조건을 정합니다.',lic:'라이선스',licP:'적절한 라이선스와 가격을 직접 협의합니다.',delivery:'전달',deliveryP:'합의된 결제 후 인스트루멘털을 준비해 직접 전달합니다.',noAuto:'자동 결제 없음.',noDownload:'자동 다운로드 없음.',personalContact:'직접 상담',requestEy:'비트 요청',found:'마음에 드는 비트를 찾았나요?',contactP:'요청을 보내세요. 자동 결제나 자동 다운로드 없이 원하는 비트에 대해 직접 상담합니다.',artist:'아티스트 / 이름',email:'이메일',beat:'비트',selectBeat:'비트 선택',message:'메시지',messagePh:'프로젝트에 대해 알려주세요...',send:'요청 보내기',mailNote:'메일 앱이 열리고 요청 내용이 준비됩니다.',footer:'오리지널 인스트루멘털',details:'비트 상세',play:'데모 재생',playing:'재생 중',modalLicense:'라이선스 & 전달',modalReq:'이 비트 요청',modalPrev:'← 이전',modalNext:'다음 →',genre:'장르',mood:'무드'},
 ar:{navStore:'متجر البيات',how:'كيف يعمل',license:'الترخيص',contact:'تواصل',heroEy:'مقطوعات أصلية · RODRIGO HITS',hero1:'اعثر على الإيقاع.',hero2:'اجعله لك.',heroP:'مقطوعات أصلية للفنانين الذين يريدون صوتًا مميزًا. استمع إلى العروض، حدد اتجاهك وأرسل طلبًا.',explore:'استكشف الإيقاعات',howBtn:'كيف يعمل',noCheckout:'لا يوجد دفع تلقائي',personal:'يتم التعامل مع كل طلب بشكل شخصي.',catalog:'الكتالوج',choose:'اختر صوتك.',saved:'المحفوظة',search:'ابحث عن الإيقاع أو النوع أو المزاج أو BPM...',allGenres:'كل الأنواع',allMoods:'كل المزاجات',min:'أقل BPM',max:'أعلى BPM',newest:'الأحدث',low:'BPM: منخفض → مرتفع',high:'BPM: مرتفع → منخفض',az:'A → Z',clear:'مسح الفلاتر',noResults:'لم يتم العثور على إيقاعات.',previous:'السابق ←',next:'التالي →',simple:'خطوات بسيطة',fromIdea:'من الفكرة\nإلى الإصدار.',howP:'اعثر على صوتك دون عملية دفع معقدة. يتم الاتفاق على الترخيص والتسليم مباشرة مع Rodrigo.',listen:'استمع',find:'اعثر على صوتك',listenP:'تصفح الكتالوج واستمع إلى العرض المناسب لفكرتك.',request:'طلب',sendReq:'إرسال طلب',requestP:'اختر الإيقاع وأخبرنا من أنت وماذا تريد أن تصنع.',connect:'تواصل',talk:'تحدث مباشرة',talkP:'يتواصل Rodrigo معك شخصيًا بخصوص الترخيص والسعر والتسليم.',licenseEy:'الترخيص والتسليم',release:'من الطلب\nإلى الإصدار.',licenseP:'تتم إدارة كل مقطوعة بشكل شخصي. لا يوجد دفع أو تنزيل تلقائي.',req:'طلب',reqP:'اختر الإيقاع وأرسل طلبك من متجر البيات.',discuss:'مناقشة',discussP:'يتواصل Rodrigo معك لتحديد شروط مشروعك.',lic:'ترخيص',licP:'يتم الاتفاق على الترخيص المناسب والسعر مباشرة معك.',delivery:'تسليم',deliveryP:'بعد الدفع المتفق عليه، يتم تجهيز المقطوعة وتسليمها مباشرة.',noAuto:'لا يوجد دفع تلقائي.',noDownload:'لا يوجد تنزيل تلقائي.',personalContact:'تواصل شخصي',requestEy:'اطلب إيقاعًا',found:'وجدت ما تبحث عنه؟',contactP:'أرسل طلبك. بدون دفع أو تنزيل تلقائي — فقط تواصل مباشر حول الإيقاع الذي تريده.',artist:'الفنان / الاسم',email:'البريد الإلكتروني',beat:'الإيقاع',selectBeat:'اختر إيقاعًا',message:'رسالة',messagePh:'أخبرنا بما يهم في مشروعك...',send:'إرسال الطلب',mailNote:'سيتم فتح تطبيق البريد مع تجهيز الطلب.',footer:'مقطوعات أصلية',details:'تفاصيل الإيقاع',play:'تشغيل العرض',playing:'يعمل الآن',modalLicense:'الترخيص والتسليم',modalReq:'اطلب هذا الإيقاع',modalPrev:'السابق ←',modalNext:'التالي →',genre:'النوع',mood:'المزاج'}
};
const UX_TEXT={
 it:{hero1:'Il tuo prossimo disco.',hero2:'Inizia qui.',heroP:'Strumentali originali per artisti che cercano identità, impatto e un sound pronto per un vero progetto. Ascolta le demo e richiedi direttamente il beat.',original:'STRUMENTALI ORIGINALI',personalLic:'LICENZA PERSONALE',directDelivery:'CONSEGNA DIRETTA',originalText:'Ogni beat è presentato come strumentale originale Rodrigo Hits.',directText:'Nessun checkout da marketplace. Parli direttamente con Rodrigo.',flexible:'FLESSIBILE',flexibleText:'Licenza e consegna vengono concordate per il tuo progetto.',requestSent:'Richiesta pronta. Si aprirà la tua app email per completare l’invio.',requestPreparing:'Preparazione della richiesta…',position:'BEAT'},
 en:{hero1:'Your next record.',hero2:'Starts here.',heroP:'Original instrumentals for artists who want identity, impact and a record-ready sound. Listen to the demos and request the beat directly.',original:'ORIGINAL BEATS',personalLic:'PERSONAL LICENSING',directDelivery:'DIRECT DELIVERY',originalText:'Every beat is presented as an original Rodrigo Hits instrumental.',directText:'No marketplace checkout. You speak directly with Rodrigo.',flexible:'FLEXIBLE',flexibleText:'License and delivery are agreed for your project.',requestSent:'Request ready. Your email app will open to complete the request.',requestPreparing:'Preparing your request…',position:'BEAT'},
 es:{hero1:'Tu próximo disco.',hero2:'Empieza aquí.',heroP:'Instrumentales originales para artistas que buscan identidad, impacto y un sonido listo para un proyecto real. Escucha las demos y solicita el beat directamente.',original:'BEATS ORIGINALES',personalLic:'LICENCIA PERSONAL',directDelivery:'ENTREGA DIRECTA',originalText:'Cada beat se presenta como una instrumental original de Rodrigo Hits.',directText:'Sin checkout de marketplace. Hablas directamente con Rodrigo.',flexible:'FLEXIBLE',flexibleText:'La licencia y la entrega se acuerdan para tu proyecto.',requestSent:'Solicitud preparada. Se abrirá tu app de correo para completar el envío.',requestPreparing:'Preparando la solicitud…',position:'BEAT'},
 fr:{hero1:'Ton prochain morceau.',hero2:'Commence ici.',heroP:'Des instrumentales originales pour les artistes qui veulent identité, impact et un son prêt pour un vrai projet. Écoute les démos et demande le beat directement.',original:'BEATS ORIGINAUX',personalLic:'LICENCE PERSONNELLE',directDelivery:'LIVRAISON DIRECTE',originalText:'Chaque beat est présenté comme une instrumentale originale Rodrigo Hits.',directText:'Pas de checkout marketplace. Tu échanges directement avec Rodrigo.',flexible:'FLEXIBLE',flexibleText:'La licence et la livraison sont définies pour ton projet.',requestSent:'Demande prête. Ton application mail va s’ouvrir pour terminer l’envoi.',requestPreparing:'Préparation de la demande…',position:'BEAT'},
 de:{hero1:'Dein nächster Track.',hero2:'Beginnt hier.',heroP:'Originale Instrumentals für Artists, die Identität, Wirkung und einen produktionstauglichen Sound suchen. Demos anhören und den Beat direkt anfragen.',original:'ORIGINALE BEATS',personalLic:'PERSÖNLICHE LIZENZ',directDelivery:'DIREKTE LIEFERUNG',originalText:'Jeder Beat wird als originales Rodrigo Hits Instrumental präsentiert.',directText:'Kein Marketplace-Checkout. Du sprichst direkt mit Rodrigo.',flexible:'FLEXIBEL',flexibleText:'Lizenz und Lieferung werden für dein Projekt vereinbart.',requestSent:'Anfrage vorbereitet. Deine Mail-App öffnet sich zum Absenden.',requestPreparing:'Anfrage wird vorbereitet…',position:'BEAT'},
 pt:{hero1:'Seu próximo disco.',hero2:'Começa aqui.',heroP:'Instrumentais originais para artistas que buscam identidade, impacto e um som pronto para um projeto real. Ouça as demos e solicite o beat diretamente.',original:'BEATS ORIGINAIS',personalLic:'LICENÇA PESSOAL',directDelivery:'ENTREGA DIRETA',originalText:'Cada beat é apresentado como um instrumental original Rodrigo Hits.',directText:'Sem checkout de marketplace. Você fala diretamente com Rodrigo.',flexible:'FLEXÍVEL',flexibleText:'Licença e entrega são combinadas para o seu projeto.',requestSent:'Solicitação pronta. Seu app de e-mail será aberto para concluir o envio.',requestPreparing:'Preparando a solicitação…',position:'BEAT'},
 zh:{hero1:'你的下一首作品。',hero2:'从这里开始。',heroP:'为追求个性、冲击力和成品级声音的艺术家打造原创伴奏。试听 Demo，并直接申请 Beat。',original:'原创 BEAT',personalLic:'私人授权',directDelivery:'直接交付',originalText:'每首 Beat 都以 Rodrigo Hits 原创伴奏呈现。',directText:'无需市场平台结账，直接与 Rodrigo 沟通。',flexible:'灵活',flexibleText:'授权与交付根据你的项目协商。',requestSent:'请求已准备好。将打开你的邮件应用完成发送。',requestPreparing:'正在准备请求…',position:'BEAT'},
 ja:{hero1:'次の作品を。',hero2:'ここから始める。',heroP:'個性とインパクト、完成度の高いサウンドを求めるアーティストのためのオリジナル・インストゥルメンタル。デモを聴いて直接リクエストできます。',original:'オリジナル BEAT',personalLic:'個別ライセンス',directDelivery:'直接納品',originalText:'すべてのビートをRodrigo Hitsのオリジナル・インストゥルメンタルとして提供。',directText:'マーケットプレイス決済なし。Rodrigoと直接やり取りします。',flexible:'柔軟',flexibleText:'ライセンスと納品はプロジェクトに合わせて決定します。',requestSent:'リクエストを準備しました。メールアプリが開きます。',requestPreparing:'リクエストを準備中…',position:'BEAT'},
 ko:{hero1:'당신의 다음 곡.',hero2:'여기서 시작하세요.',heroP:'정체성과 임팩트, 완성도 높은 사운드를 원하는 아티스트를 위한 오리지널 인스트루멘털입니다. 데모를 듣고 직접 비트를 요청하세요.',original:'오리지널 BEAT',personalLic:'개별 라이선스',directDelivery:'직접 전달',originalText:'모든 비트는 Rodrigo Hits 오리지널 인스트루멘털로 제공됩니다.',directText:'마켓플레이스 결제 없음. Rodrigo와 직접 상담합니다.',flexible:'유연한 조건',flexibleText:'프로젝트에 맞춰 라이선스와 전달을 협의합니다.',requestSent:'요청이 준비되었습니다. 이메일 앱이 열립니다.',requestPreparing:'요청 준비 중…',position:'BEAT'},
 ar:{hero1:'عملك القادم.',hero2:'يبدأ من هنا.',heroP:'مقطوعات أصلية للفنانين الذين يريدون هوية وتأثيرًا وصوتًا جاهزًا لمشروع حقيقي. استمع إلى العروض واطلب الإيقاع مباشرة.',original:'إيقاعات أصلية',personalLic:'ترخيص شخصي',directDelivery:'تسليم مباشر',originalText:'يتم تقديم كل إيقاع كمقطوعة أصلية من Rodrigo Hits.',directText:'لا يوجد دفع عبر سوق وسيط. تتواصل مباشرة مع Rodrigo.',flexible:'مرن',flexibleText:'يتم الاتفاق على الترخيص والتسليم بما يناسب مشروعك.',requestSent:'تم تجهيز الطلب. سيفتح تطبيق البريد لإكمال الإرسال.',requestPreparing:'جارٍ تجهيز الطلب…',position:'إيقاع'}
};
Object.keys(UX_TEXT).forEach(k=>Object.assign(LANGS[k],UX_TEXT[k]));
const DATA_LABELS={
  Dark:{it:'Oscuro',en:'Dark',es:'Oscuro',fr:'Sombre',de:'Dunkel',pt:'Sombrio',zh:'暗黑',ja:'ダーク',ko:'다크',ar:'داكن'},
  Atmospheric:{it:'Atmosferico',en:'Atmospheric',es:'Atmosférico',fr:'Atmosphérique',de:'Atmosphärisch',pt:'Atmosférico',zh:'氛围',ja:'アトモスフェリック',ko:'분위기 있는',ar:'جوي'},
  Chill:{it:'Rilassato',en:'Chill',es:'Relajado',fr:'Chill',de:'Entspannt',pt:'Relaxado',zh:'舒缓',ja:'チル',ko:'칠',ar:'هادئ'},
  Club:{it:'Club',en:'Club',es:'Club',fr:'Club',de:'Club',pt:'Club',zh:'俱乐部',ja:'クラブ',ko:'클럽',ar:'نادي'},
  Dark:{it:'Oscuro',en:'Dark',es:'Oscuro',fr:'Sombre',de:'Dunkel',pt:'Sombrio',zh:'暗黑',ja:'ダーク',ko:'다크',ar:'داكن'},
  Dreamy:{it:'Sognante',en:'Dreamy',es:'Soñador',fr:'Rêveur',de:'Verträumt',pt:'Sonhador',zh:'梦幻',ja:'ドリーミー',ko:'몽환적',ar:'حالم'},
  Elegant:{it:'Elegante',en:'Elegant',es:'Elegante',fr:'Élégant',de:'Elegant',pt:'Elegante',zh:'优雅',ja:'エレガント',ko:'우아한',ar:'أنيق'},
  Emotional:{it:'Emotivo',en:'Emotional',es:'Emotivo',fr:'Émotionnel',de:'Emotional',pt:'Emocional',zh:'情感',ja:'エモーショナル',ko:'감성적',ar:'عاطفي'},
  Energetic:{it:'Energico',en:'Energetic',es:'Enérgico',fr:'Énergique',de:'Energisch',pt:'Energético',zh:'活力',ja:'エネルギッシュ',ko:'에너지',ar:'حماسي'},
  Epic:{it:'Epico',en:'Epic',es:'Épico',fr:'Épique',de:'Episch',pt:'Épico',zh:'史诗',ja:'エピック',ko:'에픽',ar:'ملحمي'},
  'Feel Good':{it:'Positivo',en:'Feel Good',es:'Positivo',fr:'Feel Good',de:'Gute Laune',pt:'Alto astral',zh:'愉悦',ja:'フィールグッド',ko:'기분 좋은',ar:'إيجابي'},
  Festive:{it:'Festoso',en:'Festive',es:'Festivo',fr:'Festif',de:'Festlich',pt:'Festivo',zh:'节庆',ja:'フェスティブ',ko:'축제 분위기',ar:'احتفالي'},
  Funky:{it:'Funky',en:'Funky',es:'Funky',fr:'Funky',de:'Funky',pt:'Funky',zh:'Funky',ja:'ファンキー',ko:'펑키',ar:'فانكي'},
  Happy:{it:'Felice',en:'Happy',es:'Feliz',fr:'Joyeux',de:'Fröhlich',pt:'Feliz',zh:'快乐',ja:'ハッピー',ko:'행복한',ar:'سعيد'},
  Hard:{it:'Intenso',en:'Hard',es:'Intenso',fr:'Hard',de:'Hart',pt:'Intenso',zh:'强烈',ja:'ハード',ko:'강렬한',ar:'قوي'},
  Melodic:{it:'Melodico',en:'Melodic',es:'Melódico',fr:'Mélodique',de:'Melódico',pt:'Melódico',zh:'旋律',ja:'メロディック',ko:'멜로딕',ar:'لحني'},
  Motivational:{it:'Motivazionale',en:'Motivational',es:'Motivacional',fr:'Motivant',de:'Motivierend',pt:'Motivacional',zh:'励志',ja:'モチベーショナル',ko:'동기부여',ar:'تحفيزي'},
  Mysterious:{it:'Misterioso',en:'Mysterious',es:'Misterioso',fr:'Mystérieux',de:'Mysteriös',pt:'Misterioso',zh:'神秘',ja:'ミステリアス',ko:'신비로운',ar:'غامض'},
  Hypnotic:{it:'Ipnotico',en:'Hypnotic',es:'Hipnótico',fr:'Hypnotique',de:'Hypnotisch',pt:'Hipnótico',zh:'催眠',ja:'催眠的',ko:'최면적인',ar:'منوّم'},
  Party:{it:'Festa',en:'Party',es:'Fiesta',fr:'Fête',de:'Party',pt:'Festa',zh:'派对',ja:'パーティー',ko:'파티',ar:'حفلة'},
  Relaxed:{it:'Distensivo',en:'Relaxed',es:'Relajado',fr:'Détendu',de:'Entspannt',pt:'Relaxado',zh:'轻松',ja:'リラックス',ko:'편안한',ar:'مسترخٍ'},
  Romantic:{it:'Romantico',en:'Romantic',es:'Romántico',fr:'Romantique',de:'Romantisch',pt:'Romântico',zh:'浪漫',ja:'ロマンチック',ko:'로맨틱',ar:'رومانسي'},
  Sad:{it:'Triste',en:'Sad',es:'Triste',fr:'Triste',de:'Traurig',pt:'Triste',zh:'悲伤',ja:'サッド',ko:'슬픈',ar:'حزين'},
  Sensual:{it:'Sensuale',en:'Sensual',es:'Sensual',fr:'Sensuel',de:'Sinnlich',pt:'Sensual',zh:'性感',ja:'セクシー',ko:'관능적인',ar:'حسي'},
  Smooth:{it:'Morbido',en:'Smooth',es:'Suave',fr:'Doux',de:'Sanft',pt:'Suave',zh:'柔和',ja:'スムース',ko:'부드러운',ar:'ناعم'},
  Soulful:{it:'Soulful',en:'Soulful',es:'Soulful',fr:'Soul',de:'Soulful',pt:'Soulful',zh:'灵魂感',ja:'ソウルフル',ko:'소울풀',ar:'روحاني'},
  Street:{it:'Street',en:'Street',es:'Street',fr:'Street',de:'Street',pt:'Street',zh:'街头',ja:'ストリート',ko:'스트리트',ar:'شارعي'},
  Summer:{it:'Estivo',en:'Summer',es:'Veraniego',fr:'Estival',de:'Sommerlich',pt:'Verão',zh:'夏日',ja:'サマー',ko:'여름',ar:'صيفي'},
  Tropical:{it:'Tropicale',en:'Tropical',es:'Tropical',fr:'Tropical',de:'Tropisch',pt:'Tropical',zh:'热带',ja:'トロピカル',ko:'트로피컬',ar:'استوائي'},
  Uplifting:{it:'Coinvolgente',en:'Uplifting',es:'Inspirador',fr:'Entraînant',de:'Aufbauend',pt:'Inspirador',zh:'振奋',ja:'高揚感',ko:'고양되는',ar:'مُبهج'}
};
const MOOD_ALIASES={
  'Oscuro':'Dark','Oscura':'Dark','Sombre':'Dark','Dunkel':'Dark','Sombrio':'Dark','Sombrío':'Dark',
  'Atmosferico':'Atmospheric','Atmosférico':'Atmospheric','Atmosphérique':'Atmospheric','Atmosphärisch':'Atmospheric',
  'Rilassato':'Chill','Relajado':'Chill','Détendu':'Relaxed','Entspannt':'Relaxed','Relaxado':'Relaxed',
  'Romantico':'Romantic','Romántico':'Romantic','Romantique':'Romantic','Romântico':'Romantic',
  'Energico':'Energetic','Enérgico':'Energetic','Énergique':'Energetic','Energisch':'Energetic','Energético':'Energetic',
  'Melodico':'Melodic','Melódico':'Melodic','Mélodique':'Melodic','Melódico':'Melodic'
};
const LANG_GENRE={
  it:{'Dark Trap':'Dark Trap','Latin':'Latin','Brazilian Funk':'Brazilian Funk','Afro House':'Afro House','Reggaeton':'Reggaeton','Dembow':'Dembow','R&B':'R&B','Urban':'Urban','Trap':'Trap','Dance':'Dance','Rap':'Rap','Hip Hop':'Hip Hop','Afroreggaeton':'Afroreggaeton','Deep House':'Deep House','Merengue':'Merengue'},
  en:{'Dark Trap':'Dark Trap','Latin':'Latin','Brazilian Funk':'Brazilian Funk','Afro House':'Afro House','Reggaeton':'Reggaeton','Dembow':'Dembow','R&B':'R&B','Urban':'Urban','Trap':'Trap','Dance':'Dance','Rap':'Rap','Hip Hop':'Hip Hop','Afroreggaeton':'Afroreggaeton','Deep House':'Deep House','Merengue':'Merengue'},
  es:{'Dark Trap':'Dark Trap','Latin':'Latin','Brazilian Funk':'Brazilian Funk','Afro House':'Afro House','Reggaeton':'Reggaeton','Dembow':'Dembow','R&B':'R&B','Urban':'Urban','Trap':'Trap','Dance':'Dance','Rap':'Rap','Hip Hop':'Hip Hop','Afroreggaeton':'Afroreggaeton','Deep House':'Deep House','Merengue':'Merengue'},
  fr:{'Dark Trap':'Dark Trap','Latin':'Latin','Brazilian Funk':'Brazilian Funk','Afro House':'Afro House','Reggaeton':'Reggaeton','Dembow':'Dembow','R&B':'R&B','Urban':'Urban','Trap':'Trap','Dance':'Dance','Rap':'Rap','Hip Hop':'Hip Hop','Afroreggaeton':'Afroreggaeton','Deep House':'Deep House','Merengue':'Merengue'},
  de:{'Dark Trap':'Dark Trap','Latin':'Latin','Brazilian Funk':'Brazilian Funk','Afro House':'Afro House','Reggaeton':'Reggaeton','Dembow':'Dembow','R&B':'R&B','Urban':'Urban','Trap':'Trap','Dance':'Dance','Rap':'Rap','Hip Hop':'Hip Hop','Afroreggaeton':'Afroreggaeton','Deep House':'Deep House','Merengue':'Merengue'},
  pt:{'Dark Trap':'Dark Trap','Latin':'Latin','Brazilian Funk':'Brazilian Funk','Afro House':'Afro House','Reggaeton':'Reggaeton','Dembow':'Dembow','R&B':'R&B','Urban':'Urban','Trap':'Trap','Dance':'Dance','Rap':'Rap','Hip Hop':'Hip Hop','Afroreggaeton':'Afroreggaeton','Deep House':'Deep House','Merengue':'Merengue'},
  zh:{'Dark Trap':'Dark Trap','Latin':'Latin','Brazilian Funk':'Brazilian Funk','Afro House':'Afro House','Reggaeton':'Reggaeton','Dembow':'Dembow','R&B':'R&B','Urban':'Urban','Trap':'Trap','Dance':'Dance','Rap':'Rap','Hip Hop':'Hip Hop','Afroreggaeton':'Afroreggaeton','Deep House':'Deep House','Merengue':'Merengue'},
  ja:{'Dark Trap':'Dark Trap','Latin':'Latin','Brazilian Funk':'Brazilian Funk','Afro House':'Afro House','Reggaeton':'Reggaeton','Dembow':'Dembow','R&B':'R&B','Urban':'Urban','Trap':'Trap','Dance':'Dance','Rap':'Rap','Hip Hop':'Hip Hop','Afroreggaeton':'Afroreggaeton','Deep House':'Deep House','Merengue':'Merengue'},
  ko:{'Dark Trap':'Dark Trap','Latin':'Latin','Brazilian Funk':'Brazilian Funk','Afro House':'Afro House','Reggaeton':'Reggaeton','Dembow':'Dembow','R&B':'R&B','Urban':'Urban','Trap':'Trap','Dance':'Dance','Rap':'Rap','Hip Hop':'Hip Hop','Afroreggaeton':'Afroreggaeton','Deep House':'Deep House','Merengue':'Merengue'},
  ar:{'Dark Trap':'Dark Trap','Latin':'Latin','Brazilian Funk':'Brazilian Funk','Afro House':'Afro House','Reggaeton':'Reggaeton','Dembow':'Dembow','R&B':'R&B','Urban':'Urban','Trap':'Trap','Dance':'Dance','Rap':'Rap','Hip Hop':'Hip Hop','Afroreggaeton':'Afroreggaeton','Deep House':'Deep House','Merengue':'Merengue'}
};
const normLabel=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const MOOD_CANONICAL={};Object.keys(DATA_LABELS).forEach(k=>{MOOD_CANONICAL[normLabel(k)]=k;Object.values(DATA_LABELS[k]).forEach(v=>{MOOD_CANONICAL[normLabel(v)]=k})});Object.entries(MOOD_ALIASES).forEach(([a,k])=>MOOD_CANONICAL[normLabel(a)]=k);
const GENRE_CANONICAL={};Object.values(LANG_GENRE).forEach(map=>Object.entries(map).forEach(([k,v])=>{GENRE_CANONICAL[normLabel(k)]=k;GENRE_CANONICAL[normLabel(v)]=k}));
function canonicalMood(v){return MOOD_CANONICAL[normLabel(v)]||v}
function canonicalGenre(v){return GENRE_CANONICAL[normLabel(v)]||v}
function dl(obj){if(typeof obj==='string'){const k=canonicalMood(obj);return DATA_LABELS[k]?.[currentLang]||obj}return obj?.[currentLang]||obj?.en||obj||''}
function gl(g){const k=canonicalGenre(g);return LANG_GENRE[currentLang]?.[k]||g}
let currentLang=localStorage.getItem('rh-language')||'en';
Object.values(LANGS).forEach(x=>{x.showing=x.showing||'Showing';x.of=x.of||'of'}); Object.values(LANGS).forEach(x=>{x.requestBeat=x.requestBeat||x.modalReq||'REQUEST THIS BEAT'}); LANGS.it.beatOne='BEAT';LANGS.it.beatMany='BEAT';LANGS.en.beatOne='BEAT';LANGS.en.beatMany='BEATS';LANGS.es.beatOne='BEAT';LANGS.es.beatMany='BEATS';LANGS.fr.beatOne='BEAT';LANGS.fr.beatMany='BEATS';LANGS.de.beatOne='BEAT';LANGS.de.beatMany='BEATS';LANGS.pt.beatOne='BEAT';LANGS.pt.beatMany='BEATS';LANGS.zh.beatOne='节拍';LANGS.zh.beatMany='节拍';LANGS.ja.beatOne='ビート';LANGS.ja.beatMany='ビート';LANGS.ko.beatOne='비트';LANGS.ko.beatMany='비트';LANGS.ar.beatOne='إيقاع';LANGS.ar.beatMany='إيقاعات'; LANGS.it.showing='Mostrati';LANGS.it.of='di';LANGS.es.showing='Mostrando';LANGS.es.of='de';LANGS.fr.showing='Affichage';LANGS.fr.of='sur';LANGS.de.showing='Zeige';LANGS.de.of='von';LANGS.pt.showing='A mostrar';LANGS.pt.of='de';LANGS.zh.showing='显示';LANGS.zh.of='/';LANGS.ja.showing='表示';LANGS.ja.of='/';LANGS.ko.showing='표시';LANGS.ko.of='/';LANGS.ar.showing='عرض';LANGS.ar.of='من';
function t(k){return (LANGS[currentLang]||LANGS.en)[k]||LANGS.en[k]||k}
function gl(g){const k=canonicalGenre(g);return LANG_GENRE[currentLang]?.[k]||g}

const STORE_EMAIL="rhinstrumental@gmail.com";
const grid=document.querySelector("#grid"),count=document.querySelector("#count"),search=document.querySelector("#search"),genre=document.querySelector("#genre"),mood=document.querySelector("#mood"),sort=document.querySelector("#sort"),bpmMin=document.querySelector("#bpm-min"),bpmMax=document.querySelector("#bpm-max"),clearFilters=document.querySelector("#clear-filters"),empty=document.querySelector("#empty"),beatSelect=document.querySelector("#beat"),pagination=document.querySelector("#pagination"),pagePrev=document.querySelector("#page-prev"),pageNext=document.querySelector("#page-next"),pageNumbers=document.querySelector("#page-numbers");
const savedToggle=document.querySelector("#saved-toggle"),viewGrid=document.querySelector("#view-grid"),viewList=document.querySelector("#view-list"),resultsSummary=document.querySelector("#results-summary"),backTop=document.querySelector("#back-top");
let audio=null,playingId=null,progressTimer=null,currentPage=1,viewMode=localStorage.getItem("rh-view")||"grid";
let BEATS=[];
const BEATS_PER_PAGE=12;

fetch("beats.json", {cache:"no-cache"})
  .then(r=>{ if(!r.ok) throw new Error("beats.json not found"); return r.json(); })
  .then(data=>{
    BEATS=Array.isArray(data)?data:[];
    initBeatStore();
  })
  .catch(err=>{
    console.error(err);
    const grid=document.querySelector("#grid");
    if(grid) grid.innerHTML='<div class="empty-state">Catalog unavailable. Please check beats.json.</div>';
  });

function initBeatStore(){

let favorites=new Set(JSON.parse(localStorage.getItem("rh-favorites")||"[]"));

const genres=[...new Map(BEATS.map(b=>[canonicalGenre(b.genre),b.genre])).values()].sort((a,b)=>String(a).localeCompare(String(b)));
genres.forEach(g=>genre.insertAdjacentHTML("beforeend",`<option value="${g}">${gl(g)}</option>`));
const moods=[...new Map(BEATS.map(b=>[canonicalMood(b.mood),b.mood])).values()].sort((a,b)=>String(a).localeCompare(String(b)));
moods.forEach(m=>mood.insertAdjacentHTML("beforeend",`<option value="${m}">${dl(m)}</option>`));
BEATS.forEach((b,i)=>{b.index=i;beatSelect.insertAdjacentHTML("beforeend",`<option value="${b.id}">${b.name} — ${gl(b.genre)} · ${b.bpm} BPM</option>`)});
function norm(s){return String(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function fmt(sec){if(!isFinite(sec))return"0:00";return `${Math.floor(sec/60)}:${String(Math.floor(sec%60)).padStart(2,"0")}`}
function getFiltered(){
  const q=norm(search.value),min=bpmMin.value===""?null:Number(bpmMin.value),max=bpmMax.value===""?null:Number(bpmMax.value);
  let list=BEATS.filter(b=>(!q||norm(`${b.name} ${b.genre} ${gl(b.genre)} ${b.mood} ${dl(b.mood)} ${b.bpm}`).includes(q))&&(!genre.value||canonicalGenre(b.genre)===canonicalGenre(genre.value))&&(!mood.value||canonicalMood(b.mood)===canonicalMood(mood.value))&&(min===null||b.bpm>=min)&&(max===null||b.bpm<=max));
  if(savedToggle?.classList.contains("active"))list=list.filter(b=>favorites.has(b.id));
  if(sort.value==="low")list.sort((a,b)=>a.bpm-b.bpm);
  if(sort.value==="high")list.sort((a,b)=>b.bpm-a.bpm);
  if(sort.value==="az")list.sort((a,b)=>a.name.localeCompare(b.name));
  if(sort.value==="new")list.sort((a,b)=>(a.index||0)-(b.index||0));
  return list;
}
function favoriteButton(b){return `<button class="favorite-btn${favorites.has(b.id)?" active":""}" data-favorite="${b.id}" aria-label="${favorites.has(b.id)?"Remove":"Save"} ${b.name} from favorites" aria-pressed="${favorites.has(b.id)}">${favorites.has(b.id)?"♥":"♡"}</button>`}
function render(){
  const list=getFiltered(),total=list.length,totalPages=Math.max(1,Math.ceil(total/BEATS_PER_PAGE));
  if(currentPage>totalPages)currentPage=totalPages;
  const start=(currentPage-1)*BEATS_PER_PAGE,pageList=list.slice(start,start+BEATS_PER_PAGE);
  count.textContent=`${total} ${total===1?t("beatOne"):t("beatMany")}`;
  if(resultsSummary)resultsSummary.textContent=total?`${t("showing")||"Showing"} ${start+1}–${Math.min(start+BEATS_PER_PAGE,total)} ${t("of")||"of"} ${total}`:t("noResults");
  grid.classList.toggle("list-view",viewMode==="list");
  grid.innerHTML=pageList.map(b=>`<article class="card" data-beat="${b.id}">
    <div class="cover"><img src="covers/${b.id}.jpg" alt="${b.name} cover" loading="lazy" decoding="async" width="800" height="800"><span class="cover-tag">ORIGINAL</span>${favoriteButton(b)}<strong>${b.name}</strong></div>
    <div class="info"><div class="row"><span class="name">${b.name}</span><span class="meta bpm">${b.bpm} BPM</span></div><div class="meta details">${gl(b.genre)} <i>·</i> ${dl(DATA_LABELS[b.mood])}</div>
      <div class="player" id="player-${b.id}"><button class="play" data-id="${b.id}" aria-label="Play ${b.name}"><span class="play-icon">▶</span><span class="play-label">${t("play")}</span></button><div class="track"><div class="track-bar"><span></span></div><div class="time"><span class="current">0:00</span><span class="duration">0:00</span></div></div></div>
      <button class="request" data-id="${b.id}">${t("requestBeat")} <span>→</span></button>
    </div></article>`).join("");
  empty.hidden=total!==0;
  renderPagination(totalPages,total);
  document.querySelectorAll(".play").forEach(btn=>btn.onclick=e=>{e.stopPropagation();play(btn)});
  document.querySelectorAll(".request").forEach(btn=>btn.onclick=e=>{e.stopPropagation();requestBeat(btn.dataset.id)});
  document.querySelectorAll(".favorite-btn").forEach(btn=>btn.onclick=e=>{e.stopPropagation();toggleFavorite(btn.dataset.favorite)});
}
function renderPagination(totalPages,total){
  pagination.hidden=total<=BEATS_PER_PAGE;
  pagePrev.disabled=currentPage<=1;pageNext.disabled=currentPage>=totalPages;pagePrev.textContent=t("previous");pageNext.textContent=t("next");pageNumbers.innerHTML="";
  const pages=[];if(totalPages<=5){for(let i=1;i<=totalPages;i++)pages.push(i)}else{pages.push(1);if(currentPage>3)pages.push("...");for(let i=Math.max(2,currentPage-1);i<=Math.min(totalPages-1,currentPage+1);i++)pages.push(i);if(currentPage<totalPages-2)pages.push("...");pages.push(totalPages)}
  pages.forEach(p=>{if(p==="..."){pageNumbers.insertAdjacentHTML("beforeend",`<span class="page-dots">…</span>`);return}const b=document.createElement("button");b.type="button";b.className=`page-number${p===currentPage?" active":""}`;b.textContent=p;b.setAttribute("aria-label",`Page ${p}`);if(p===currentPage)b.setAttribute("aria-current","page");b.onclick=()=>{currentPage=p;render();scrollToStore()};pageNumbers.appendChild(b)});
}
function scrollToStore(){document.querySelector("#store").scrollIntoView({behavior:"smooth",block:"start"})}
function resetPlayer(){clearInterval(progressTimer);progressTimer=null;document.querySelectorAll(".play").forEach(btn=>{btn.classList.remove("playing");btn.querySelector(".play-icon")?.replaceChildren(document.createTextNode("▶"));btn.querySelector(".play-label")?.replaceChildren(document.createTextNode("PLAY DEMO"))});document.querySelectorAll(".track-bar span").forEach(x=>x.style.width="0%");document.querySelectorAll(".current").forEach(x=>x.textContent="0:00")}
function play(btn){const b=BEATS.find(x=>x.id===btn.dataset.id);if(!b)return;if(playingId===b.id&&audio){audio.paused?audio.play():audio.pause();updateButton(btn);return}if(audio){audio.pause();audio=null}resetPlayer();audio=new Audio();audio.preload="none";audio.src=`audio/${b.id}.mp3`;playingId=b.id;btn.classList.add("playing");btn.querySelector(".play-icon").textContent="❚❚";btn.querySelector(".play-label").textContent="PLAYING";audio.addEventListener("loadedmetadata",()=>{const d=document.querySelector(`#player-${b.id} .duration`);if(d)d.textContent=fmt(audio.duration)});audio.addEventListener("timeupdate",()=>{const p=document.querySelector(`#player-${b.id}`);if(p){p.querySelector(".track-bar span").style.width=`${(audio.currentTime/audio.duration)*100}%`;p.querySelector(".current").textContent=fmt(audio.currentTime)}});audio.onended=()=>{audio=null;playingId=null;resetPlayer()};audio.play().catch(()=>{alert(`Add ${b.id}.mp3 to the audio folder to activate this demo.`);audio=null;playingId=null;resetPlayer()})}
function updateButton(btn){if(!audio)return;const paused=audio.paused;btn.classList.toggle("playing",!paused);btn.querySelector(".play-icon").textContent=paused?"▶":"❚❚";btn.querySelector(".play-label").textContent=paused?"PLAY DEMO":"PLAYING"}
document.querySelectorAll(".track-bar").forEach(()=>{});
grid.addEventListener("click",e=>{const fav=e.target.closest(".favorite-btn");if(fav)return;const target=e.target.closest(".cover,.name");if(!target)return;const card=target.closest(".card");if(card)openModal(card.dataset.beat)});
document.addEventListener("click",e=>{const bar=e.target.closest(".track-bar");if(!bar||!audio||!audio.duration)return;const r=bar.getBoundingClientRect();audio.currentTime=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*audio.duration});
function toggleFavorite(id){if(favorites.has(id))favorites.delete(id);else favorites.add(id);localStorage.setItem("rh-favorites",JSON.stringify([...favorites]));updateFavoriteCount();render()}
function updateFavoriteCount(){if(savedToggle)savedToggle.innerHTML=`♡ ${t("saved")} <span>${favorites.size}</span>`}
function requestBeat(id){beatSelect.value=id;document.querySelector("#contact").scrollIntoView({behavior:"smooth",block:"start"});setTimeout(()=>document.querySelector("#name")?.focus(),650)}
// Modal
const beatModal=document.querySelector("#beat-modal"),modalCover=document.querySelector("#modal-cover"),modalName=document.querySelector("#modal-name"),modalGenre=document.querySelector("#modal-genre"),modalMood=document.querySelector("#modal-mood"),modalBpm=document.querySelector("#modal-bpm"),modalRequest=document.querySelector("#modal-request"),modalPlay=document.querySelector("#modal-play"),modalPlayIcon=document.querySelector("#modal-play-icon"),modalLabel=document.querySelector("#modal-player-label"),modalProgress=document.querySelector("#modal-progress"),modalCurrent=document.querySelector("#modal-current"),modalDuration=document.querySelector("#modal-duration"),modalPrev=document.querySelector("#modal-prev"),modalNext=document.querySelector("#modal-next"),modalPosition=document.querySelector("#modal-position"),requestStatus=document.querySelector("#request-status");
let modalAudio=null,modalBeatId=null;
function modalFmt(sec){return fmt(sec)}
function resetModalPlayer(){if(modalAudio){modalAudio.pause();modalAudio=null}modalPlayIcon.textContent="▶";modalLabel.textContent=t("play");modalProgress.style.width="0%";modalCurrent.textContent="0:00";modalDuration.textContent="0:00"}
function startModalPlayer(id){if(modalBeatId!==id)return;if(modalAudio){modalAudio.paused?modalAudio.play():modalAudio.pause();updateModalButton();return}modalAudio=new Audio();modalAudio.preload="none";modalAudio.src=`audio/${id}.mp3`;modalAudio.addEventListener("loadedmetadata",()=>modalDuration.textContent=modalFmt(modalAudio.duration));modalAudio.addEventListener("timeupdate",()=>{modalProgress.style.width=`${(modalAudio.currentTime/modalAudio.duration)*100}%`;modalCurrent.textContent=modalFmt(modalAudio.currentTime)});modalAudio.onended=()=>resetModalPlayer();modalAudio.play().then(updateModalButton).catch(()=>{alert(`Add ${id}.mp3 to the audio folder to activate this demo.`);resetModalPlayer()})}
function updateModalButton(){const paused=modalAudio?.paused;modalPlayIcon.textContent=paused?"▶":"❚❚";modalLabel.textContent=paused?"PLAY DEMO":"PLAYING"}
function getModalList(){return getFiltered()}
function updateModalNavigation(){const list=getModalList(),i=list.findIndex(b=>b.id===modalBeatId);modalPrev.disabled=i<=0;modalNext.disabled=i<0||i>=list.length-1}
function showBeatInModal(id){const b=BEATS.find(x=>x.id===id);if(!b)return;resetModalPlayer();modalBeatId=id;modalCover.style.backgroundImage=`url("covers/${b.id}.jpg")`;modalName.textContent=b.name;modalGenre.textContent=gl(b.genre);modalMood.textContent=dl(DATA_LABELS[b.mood]);modalBpm.textContent=`${b.bpm} BPM`;modalRequest.dataset.id=b.id;updateModalNavigation();const ml=getModalList(),mi=ml.findIndex(x=>x.id===b.id);if(modalPosition)modalPosition.textContent=`${t("position")} ${mi+1} / ${ml.length}`}
function openModal(id){showBeatInModal(id);beatModal.classList.add("open");beatModal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open")}
function closeModal(){resetModalPlayer();modalBeatId=null;beatModal.classList.remove("open");beatModal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open")}
modalPlay.onclick=()=>startModalPlayer(modalBeatId);document.querySelector(".modal-track").onclick=e=>{if(!modalAudio?.duration)return;const r=e.currentTarget.getBoundingClientRect();modalAudio.currentTime=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*modalAudio.duration};
modalPrev.onclick=()=>{const l=getModalList(),i=l.findIndex(b=>b.id===modalBeatId);if(i>0){showBeatInModal(l[i-1].id)}};modalNext.onclick=()=>{const l=getModalList(),i=l.findIndex(b=>b.id===modalBeatId);if(i>=0&&i<l.length-1)showBeatInModal(l[i+1].id)};
document.querySelector(".beat-modal-close").onclick=closeModal;document.querySelector(".beat-modal-backdrop").onclick=closeModal;modalRequest.onclick=()=>{const id=modalRequest.dataset.id;closeModal();requestBeat(id)};document.addEventListener("keydown",e=>{if(e.key==="Escape"&&beatModal.classList.contains("open"))closeModal();if(beatModal.classList.contains("open")&&e.key==="ArrowLeft"&&!modalPrev.disabled)modalPrev.click();if(beatModal.classList.contains("open")&&e.key==="ArrowRight"&&!modalNext.disabled)modalNext.click()});
// Controls
[search,bpmMin,bpmMax].forEach(x=>x.addEventListener("input",()=>{currentPage=1;render()}));[genre,mood,sort].forEach(x=>x.addEventListener("change",()=>{currentPage=1;render()}));clearFilters.onclick=()=>{search.value="";genre.value="";mood.value="";bpmMin.value="";bpmMax.value="";sort.value="new";savedToggle?.classList.remove("active");currentPage=1;render()};savedToggle?.addEventListener("click",()=>{savedToggle.classList.toggle("active");currentPage=1;render()});
viewGrid?.addEventListener("click",()=>{viewMode="grid";localStorage.setItem("rh-view",viewMode);viewGrid.classList.add("active");viewList.classList.remove("active");render()});viewList?.addEventListener("click",()=>{viewMode="list";localStorage.setItem("rh-view",viewMode);viewList.classList.add("active");viewGrid.classList.remove("active");render()});
pagePrev.onclick=()=>{if(currentPage>1){currentPage--;render();scrollToStore()}};pageNext.onclick=()=>{const t=Math.ceil(getFiltered().length/BEATS_PER_PAGE);if(currentPage<t){currentPage++;render();scrollToStore()}};backTop?.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"}));
document.querySelector("#form").onsubmit=e=>{e.preventDefault();const b=BEATS.find(x=>x.id===beatSelect.value),subject=encodeURIComponent(`Beat Request — ${b?b.name:beatSelect.value}`),body=encodeURIComponent(`Artist / Name: ${document.querySelector("#name").value}\nEmail: ${document.querySelector("#email").value}\nBeat: ${b?b.name+" ("+b.id+")":beatSelect.value}\n\nMessage:\n${document.querySelector("#message").value}`);if(requestStatus){requestStatus.hidden=false;requestStatus.textContent=t("requestPreparing");requestStatus.classList.add("show")}setTimeout(()=>{if(requestStatus)requestStatus.textContent=t("requestSent");location.href=`mailto:${STORE_EMAIL}?subject=${subject}&body=${body}`},250)};

function applyLanguage(){
  const lang=currentLang, rtl=lang==='ar';
  document.documentElement.lang=lang; document.documentElement.dir=rtl?'rtl':'ltr';
  document.title=`Rodrigo Hits — Beat Store`;
  const q=(sel,txt)=>{const el=document.querySelector(sel);if(el&&txt!==undefined)el.textContent=txt};
  q('nav a[href="#store"]',t('navStore'));q('nav a[href="#how"]',t('how'));q('nav a[href="#license"]',t('license'));q('nav a[href="#contact"]',t('contact'));
  q('.hero .eyebrow',t('heroEy'));q('.hero h1',t('hero1')+'\n');
  const h1=document.querySelector('.hero h1');if(h1)h1.innerHTML=`${t('hero1')}<br><em>${t('hero2')}</em>`;
  q('.hero p',t('heroP'));q('.hero-proof span:nth-child(1)',t('original'));q('.hero-proof span:nth-child(2)',t('personalLic'));q('.hero-proof span:nth-child(3)',t('directDelivery'));q('.hero-actions .btn',t('explore')+' ↓');q('.hero-actions .text-link',t('howBtn')+' →');q('.hero-note strong',t('noCheckout'));q('.hero-note span',t('personal'));
  q('.section-head .eyebrow',t('catalog'));q('.section-head h2',t('choose'));q('#search',t('search'));
  genre.options[0].textContent=t('allGenres');mood.options[0].textContent=t('allMoods');bpmMin.placeholder=t('min');bpmMax.placeholder=t('max');
  const go=[...genre.options].slice(1);go.forEach(o=>o.textContent=gl(o.value));const mo=[...mood.options].slice(1);mo.forEach(o=>o.textContent=dl(o.value));
  const so=[['new',t('newest')],['low',t('low')],['high',t('high')],['az',t('az')]];[...sort.options].forEach((o,i)=>{if(so[i])o.textContent=so[i][1]});q('#clear-filters',t('clear')+' ×');
  q('.how-title .eyebrow',t('simple'));const ht=document.querySelector('.how-title h2');if(ht)ht.innerHTML=t('fromIdea').replace('\n','<br>');q('.how-title p',t('howP'));q('.trust-strip div:nth-child(1) strong',t('original'));q('.trust-strip div:nth-child(1) span',t('originalText'));q('.trust-strip div:nth-child(2) strong',t('directDelivery'));q('.trust-strip div:nth-child(2) span',t('directText'));q('.trust-strip div:nth-child(3) strong',t('flexible'));q('.trust-strip div:nth-child(3) span',t('flexibleText'));
  const arts=document.querySelectorAll('.steps article');if(arts.length>=3){q('.steps article:nth-child(1) .step-top span',t('listen'));q('.steps article:nth-child(1) h3',t('find'));q('.steps article:nth-child(1) p',t('listenP'));q('.steps article:nth-child(2) .step-top span',t('request'));q('.steps article:nth-child(2) h3',t('sendReq'));q('.steps article:nth-child(2) p',t('requestP'));q('.steps article:nth-child(3) .step-top span',t('connect'));q('.steps article:nth-child(3) h3',t('talk'));q('.steps article:nth-child(3) p',t('talkP'));}
  q('.license-head .eyebrow',t('licenseEy'));const lh=document.querySelector('.license-head h2');if(lh)lh.innerHTML=t('release').replace('\n','<br>');q('.license-head p',t('licenseP'));
  const la=document.querySelectorAll('.license-steps article');const lk=[['req','reqP'],['discuss','discussP'],['lic','licP'],['delivery','deliveryP']];la.forEach((a,i)=>{if(lk[i]){q(`.license-steps article:nth-child(${i+1}) h3`,t(lk[i][0]));q(`.license-steps article:nth-child(${i+1}) p`,t(lk[i][1]));}});
  const note=document.querySelector('.license-note');if(note){note.innerHTML=`<strong>${t('noAuto')}</strong><span>${t('noDownload')}</span><span>${t('personalContact')}</span>`}
  q('.contact-copy .eyebrow',t('requestEy'));q('.contact-copy h2',t('found'));q('.contact-copy p',t('contactP'));
  const labels=document.querySelectorAll('#form label');if(labels.length>=4){labels[0].childNodes[0].textContent=t('artist');labels[1].childNodes[0].textContent=t('email');labels[2].childNodes[0].textContent=t('beat');labels[3].childNodes[0].textContent=t('message');}
  q('#form button',t('send')+' →');q('#form small',t('mailNote'));const msg=document.querySelector('#message');if(msg)msg.placeholder=t('messagePh');
  const bs=document.querySelector('#beat');if(bs){bs.options[0].textContent=t('selectBeat');[...bs.options].slice(1).forEach(o=>{const b=BEATS.find(x=>x.id===o.value);if(b)o.textContent=`${b.name} — ${gl(b.genre)} · ${b.bpm} BPM`})}
  const ft=document.querySelector('footer div:first-child span');if(ft)ft.textContent=t('footer');
  q('.beat-modal .eyebrow',t('details'));q('#modal-player-label',t('play'));q('.modal-license-title',t('modalLicense'));q('#modal-prev',t('modalPrev'));q('#modal-next',t('modalNext'));const mr=document.querySelector('#modal-request');if(mr)mr.innerHTML=`${t("modalReq")} <span>→</span>`;
  document.querySelector('#language-select').value=currentLang;
  render();
}
const languageSelect=document.querySelector('#language-select');
languageSelect?.addEventListener('change',()=>{currentLang=languageSelect.value;localStorage.setItem('rh-language',currentLang);applyLanguage()});
if(viewMode==="list"){viewList?.classList.add("active");viewGrid?.classList.remove("active")}else{viewGrid?.classList.add("active");viewList?.classList.remove("active")}
updateFavoriteCount();applyLanguage();
}
